import { UserLdap } from './user-ldap';

export const LDAP_USERS: UserLdap[] = [
  {
    id: 1,
    login: 'test.v1',
    nom: 'V1',
    prenom: 'Test',
    nomComplet: 'V1 Test',
    motDePasse: '123',
    mail: 'test.v1@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 1234,
    employeNiveau: 120,
    dateEmbauche: '2020-01-01',
    publisherId: 1,
    active: true,
  },
  {
    id: 2,
    login: 'test.v2',
    nom: 'V2',
    prenom: 'Test',
    nomComplet: 'V2 Test',
    motDePasse: '123',
    mail: 'test.v2@epsi.fr',
    role: 'ROLE_USER',
    employeNumero: 2234,
    employeNiveau: 220,
    dateEmbauche: '2020-02-02',
    publisherId: 2,
    active: false,
  },
  {
  id: 3,
  login: 'test.v3',
  nom: 'V3',
  prenom: 'Test',
  nomComplet: 'V3 Test',
  motDePasse: '123',
  mail: 'test.v1@epsi.fr',
  role: 'ROLE_USER',
  employeNumero: 1235,
  employeNiveau: 120,
  dateEmbauche: '2020-01-01',
  publisherId: 3,
  active: true,
},
{
  id: 4,
  login: 'test.v4',
  nom: 'V4',
  prenom: 'Test',
  nomComplet: 'V4 Test',
  motDePasse: '123',
  mail: 'test.v1@epsi.fr',
  role: 'ROLE_USER',
  employeNumero: 1255,
  employeNiveau: 120,
  dateEmbauche: '2020-01-01',
  publisherId: 4,
  active: false,
},

{
  id: 5,
  login: 'test.v5',
  nom: 'V5',
  prenom: 'Test',
  nomComplet: 'V5 Test',
  motDePasse: '123',
  mail: 'test.v1@epsi.fr',
  role: 'ROLE_USER',
  employeNumero: 1255,
  employeNiveau: 130,
  dateEmbauche: '2020-01-01',
  publisherId: 5,
  active: false,
},
];
